### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by arjunmenon** [ayjayt/uxmux#2]
Hey interesting project.
I was able to build this, but when supplying a basic hello world html and css(just one header and css with font size), i didnt see any output. Only a msg in the terminal to right click to view . But doing that shows nothing.

Any hints? Can this work on latest linux kernels?

**Comment by ayjayt** [comment]
Yes yes, this whole user is archived, really


There are really four parts

a) open up linux's framebuffer api, not sure if that exists anymore
b) capture mouse
c) set up light html
c) connect a, b, and c

check to se if the files opened in https://github.com/ayjayt/uxmux/blob/master/uxmux.h still exists on your machine, you may have to enable things

otherwise, i can't really provide support for this, its wicked old and its just not the direction the industry went.

thanks!
